### ISSUE TITLE
[feat] 앱 헤더 컴포넌트, 사이드바, 고객페이지 구현

### ISSUE THREAD

**Issue by hyundonny** [wanted-pre-onboading-10/ncnc-app#1]
# TASK CARD

Task Description : 공통적으로 활용할 헤더 컴포넌트, 사이드바 및 고객페이지 구현

Date : 2022-02-14

## to-do

- [x] 제목+돌아가기 헤더 컴포넌트 구현 (제목 빈 경우도 고려)
- [x] 홈페이지 헤더 컴포넌트 구현 (좌측 햄버거 메뉴, 제목은 니콘내콘)
- [x] 사이드바 열었을 때 나타나는 헤더 컴포넌트 구현 (제목 + X)
- [x] 사이드바 구현
- [x] 고객페이지 구현
