### ISSUE TITLE
[docs] README 작성

### ISSUE THREAD

**Issue by hyundonny** [wanted-pre-onboading-10/ncnc-app#10]
# TASK CARD

Task Description : README 작성

Date : 2022-02-16

## to-do

- [x] 과제 내용 요약, bullet point로 정리
- [x] 팀원 별 역할 정리
- [x] 사용 기술 및 스택 정리
- [x] 로컬 환경 구동
