### ISSUE TITLE
[feat] 브랜드 페이지 구현

### ISSUE THREAD

**Issue by tae100k** [wanted-pre-onboading-10/ncnc-app#3]
# TASK CARD

Task Description : 브랜드 페이지 구현

Date : 2022.02.14

## to-do
[에러]
- [x] scss파일이 import되지 않음

[3*3 브랜드 격자판]
- [x] 격자판 구현
- [x] 격자판 type 지정

[상단 메뉴선택바]
- [x] 상단바 구현
- [x] 상단 격자판 type지정

[SSR]
- [x] SSR로 카테고리 api가져오기
- [x] SSR로 브랜드 api가져오기
